Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'cm_challenge/*'

Style/BlockComments:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'utils/seeder.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/*'
